title: Dibakar Dhar
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Research Scholar in High Energy & Astro-particle Physics. 
  Specializing in AMPT simulations, QGP, and Strange Stars.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dibakardhar.github.io" 

# Build settings
theme: jekyll-theme-slate # This is a clean, professional dark theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
